tasks:
  - command: sudo apt install  libvirt-clients libvirt-daemon-system bridge-utils virt-manager libguestfs-tools -y && docker build -t docker-osx --build-arg SHORTNAME=ventura . && docker run -it --device /dev/kvm  -p 50922:10022 -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" -e GENERATE_UNIQUE=true -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' docker-osx

image:
  file: .gitpod.Dockerfile #sickcodes/docker-osx:latest
 
vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
